theme: jekyll-theme-minimal
title: PogoSearch
description: A private Android app for creating search commands for Pok√©mon GO
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/MuschasGracias6/PoGoSearch
